# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a37baeedbfb8dfbbb5e3cb4bc200c6d82965636e3b8c6d0e04e79b4c929d697c417a5286ad670167e7cfea153e120ceb5511fb8d17839dd7a3e589c3a9639a3

test:
  secret_key_base: 3c7fe6f56ec7f0c1f4d7983294057c07cbf6fd126e8e1711a20821f8946128619397648d8d0a38e4c082f7174ac88e661c8bddc9381843a7ce65faa36f2fb19a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
